### PR TITLE
Add check for Kafka resources

### PR DESCRIPTION
**Pull request by kvijai82**
Add checks for kafka, kafkaclaim, kafkacomposite, and kafkauser

### CODE REVIEW

**Review by taylormgeorge91 — CHANGES_REQUESTED** [review]
The example should include the name and namespace that are in our docs. I think this would be `cp4waiops` namespace and `ibm-cp-watson-aiops`

**Comment by taylormgeorge91** [comment]
Great addition! Especially when there are install related problems this will help quickly identify the area to focus on!

**Comment by kvijai82** [comment]
> The example should include the name and namespace that are in our docs. I think this would be `cp4waiops` namespace and `ibm-cp-watson-aiops`

Good point.  Updated.

**Review by taylormgeorge91 — CHANGES_REQUESTED** [review]
Update version by patch

**Pull request closed without merging**
