### PR TITLE
Update status tool for 4.4

### PR DESCRIPTION
**Pull request by siyer-123**
* Fixed redis for 4.4 to work with new redis
* Updated status tool to address Bedrock changes in v4.4
* Updated script version to 0.0.26

### CODE REVIEW

**Comment by siyer-123** [comment]
The changes are in `oc waiops status-all` and `status-upgrade`:

`oc waiops status-all`:

```
# oc waiops status-all

Cloud Pak for AIOps v4.4 installation status:
______________________________________________________________
Installation instances:

NAME                 PHASE     LICENSE    STORAGECLASS   STORAGECLASSLARGEBLOCK   AGE
aiops-installation   Running   Accepted   rook-cephfs    rook-ceph-rbd            124m

______________________________________________________________
ZenService instances:

KIND         NAME                 NAMESPACE   VERSION   STATUS      PROGRESS   MESSAGE
ZenService   iaf-zen-cpdservice   katamari    5.1.0     Completed   100%       The Current Operation Is Completed

______________________________________________________________
Kafka and Elasticsearch instances:

KIND    NAMESPACE   NAME         STATUS
Kafka   katamari    iaf-system   True

KIND            NAMESPACE   NAME         STATUS
Elasticsearch   katamari    iaf-system   True

______________________________________________________________
IRCore and AIOpsAnalyticsOrchestrator instances:

KIND                  NAMESPACE   NAME    VERSION   STATUS   MESSAGE
IssueResolutionCore   katamari    aiops   4.4.0     Ready    All Services Ready

KIND                         NAMESPACE   NAME    VERSION   STATUS   MESSAGE
AIOpsAnalyticsOrchestrator   katamari    aiops   4.4.0     Ready    All Services Ready

______________________________________________________________
LifecycleService instances:

KIND               NAMESPACE   NAME    VERSION   STATUS   MESSAGE
LifecycleService   katamari    aiops   4.4.0     Ready    All Services Ready

______________________________________________________________
BaseUI instances:

KIND     NAMESPACE   NAME              VERSION   STATUS   MESSAGE
BaseUI   katamari    baseui-instance   4.4.0     True     Ready

______________________________________________________________
AIManager, ASM, AIOpsEdge, and AIOpsUI instances:

KIND        NAMESPACE   NAME        VERSION   STATUS      MESSAGE
AIManager   katamari    aimanager   4.4.0     Completed   AI Manager is ready

KIND   NAMESPACE   NAME             VERSION   STATUS
ASM    katamari    aiops-topology   2.20.0    OK

KIND        NAMESPACE   NAME        STATUS       MESSAGE
AIOpsEdge   katamari    aiopsedge   Configured   all critical components are reporting healthy

KIND      NAMESPACE   NAME               VERSION   STATUS   MESSAGE
AIOpsUI   katamari    aiopsui-instance   4.4.0     True     Ready

______________________________________________________________
Kong instances:

KIND   NAMESPACE   NAME      STATUS   MESSAGE
Kong   katamari    gateway   True     <none>

______________________________________________________________
Postgres instances:

KIND      NAMESPACE   NAME                              STATUS
Cluster   katamari    aiops-installation-edb-postgres   Cluster in healthy state
Cluster   katamari    zen-metastore-edb                 Cluster in healthy state

______________________________________________________________
Secure Tunnel instances:

KIND     NAMESPACE   NAME         STATUS
Tunnel   katamari    sre-tunnel   True

______________________________________________________________
CSVs from katamari namespace:

NAME                                     DISPLAY                VERSION              REPLACES   PHASE
aimanager-operator.v4.4.0-202401112245   IBM AIOps AI Manager   4.4.0-202401112245              Succeeded

NAME                                     DISPLAY          VERSION              REPLACES   PHASE
aiopsedge-operator.v4.4.0-202401112245   IBM AIOps Edge   4.4.0-202401112245              Succeeded

NAME                               DISPLAY                             VERSION              REPLACES   PHASE
asm-operator.v4.4.0-202401112245   IBM Netcool Agile Service Manager   4.4.0-202401112245              Succeeded

NAME                                  DISPLAY                                            VERSION              REPLACES   PHASE
ibm-aiops-ir-ai.v4.4.0-202401112245   IBM Watson AIOps Issue Resolution AI & Analytics   4.4.0-202401112245              Succeeded

NAME                                    DISPLAY                                  VERSION              REPLACES   PHASE
ibm-aiops-ir-core.v4.4.0-202401112245   IBM Watson AIOps Issue Resolution Core   4.4.0-202401112245              Succeeded

NAME                                         DISPLAY                                    VERSION              REPLACES   PHASE
ibm-aiops-ir-lifecycle.v4.4.0-202401112245   IBM Cloud Pak for Watson AIOps Lifecycle   4.4.0-202401112245              Succeeded

NAME                                         DISPLAY                   VERSION              REPLACES   PHASE
ibm-aiops-orchestrator.v4.4.0-202401112245   IBM Cloud Pak for AIOps   4.4.0-202401112245              Succeeded

NAME                             DISPLAY       VERSION   REPLACES   PHASE
ibm-automation-elastic.v1.3.15   IBM Elastic   1.3.15               Succeeded

NAME                           DISPLAY                           VERSION   REPLACES   PHASE
ibm-automation-flink.v1.3.15   IBM Automation Foundation Flink   1.3.15               Succeeded

NAME                  DISPLAY                 VERSION   REPLACES   PHASE
ibm-redis-cp.v1.1.4   ibm-redis-cp-operator   1.1.4                Succeeded

NAME                                 DISPLAY                               VERSION   REPLACES   PHASE
ibm-common-service-operator.v4.3.1   IBM Cloud Pak foundational services   4.3.1                Succeeded

NAME                                      DISPLAY                         VERSION              REPLACES   PHASE
ibm-management-kong.v4.4.0-202401112245   IBM Internal - IBM AIOps Kong   4.4.0-202401112245              Succeeded

NAME                                             DISPLAY             VERSION              REPLACES   PHASE
ibm-secure-tunnel-operator.v4.4.0-202401112245   IBM Secure Tunnel   4.4.0-202401112245              Succeeded

NAME                                               DISPLAY        VERSION              REPLACES   PHASE
ibm-watson-aiops-ui-operator.v4.4.0-202401112245   IBM AIOps UI   4.4.0-202401112245              Succeeded

NAME                              DISPLAY                       VERSION   REPLACES                          PHASE
cloud-native-postgresql.v1.18.7   EDB Postgres for Kubernetes   1.18.7    cloud-native-postgresql.v1.18.6   Succeeded

NAME                               DISPLAY            VERSION   REPLACES   PHASE
ibm-cert-manager-operator.v4.2.1   IBM Cert Manager   4.2.1                Succeeded

NAME                           DISPLAY         VERSION   REPLACES   PHASE
ibm-commonui-operator.v4.3.0   Ibm Common UI   4.3.0                Succeeded

NAME                         DISPLAY               VERSION   REPLACES   PHASE
ibm-events-operator.v4.9.0   IBM Events Operator   4.9.0                Succeeded

NAME                      DISPLAY           VERSION   REPLACES   PHASE
ibm-iam-operator.v4.3.1   IBM IM Operator   4.3.1                Succeeded

NAME                          DISPLAY                VERSION   REPLACES   PHASE
ibm-mongodb-operator.v4.2.1   IBM MongoDB Operator   4.2.1                Succeeded

NAME                      DISPLAY           VERSION   REPLACES   PHASE
ibm-zen-operator.v5.1.0   IBM Zen Service   5.1.0                Succeeded

NAME                                          DISPLAY                                VERSION   REPLACES   PHASE
operand-deployment-lifecycle-manager.v4.2.2   Operand Deployment Lifecycle Manager   4.2.2                Succeeded

______________________________________________________________
Subscriptions from katamari namespace:

NAME                 PACKAGE              SOURCE                  CHANNEL
aimanager-operator   aimanager-operator   ibm-cp-waiops-catalog   v4.4

NAME                 PACKAGE              SOURCE                  CHANNEL
aiopsedge-operator   aiopsedge-operator   ibm-cp-waiops-catalog   v4.4

NAME           PACKAGE        SOURCE                  CHANNEL
asm-operator   asm-operator   ibm-cp-waiops-catalog   v4.4

NAME                     PACKAGE                  SOURCE                  CHANNEL
ibm-aiops-orchestrator   ibm-aiops-orchestrator   ibm-cp-waiops-catalog   v4.4

NAME                     PACKAGE                  SOURCE                  CHANNEL
ibm-automation-elastic   ibm-automation-elastic   ibm-cp-waiops-catalog   v1.3

NAME                   PACKAGE                SOURCE                  CHANNEL
ibm-automation-flink   ibm-automation-flink   ibm-cp-waiops-catalog   v1.3

NAME                  PACKAGE               SOURCE                  CHANNEL
ibm-management-kong   ibm-management-kong   ibm-cp-waiops-catalog   v4.4

NAME                         PACKAGE                      SOURCE                  CHANNEL
ibm-secure-tunnel-operator   ibm-secure-tunnel-operator   ibm-cp-waiops-catalog   v4.4

NAME                           PACKAGE                        SOURCE                  CHANNEL
ibm-watson-aiops-ui-operator   ibm-watson-aiops-ui-operator   ibm-cp-waiops-catalog   v4.4

NAME             PACKAGE           SOURCE                  CHANNEL
ir-ai-operator   ibm-aiops-ir-ai   ibm-cp-waiops-catalog   v4.4

NAME               PACKAGE             SOURCE                  CHANNEL
ir-core-operator   ibm-aiops-ir-core   ibm-cp-waiops-catalog   v4.4

NAME                    PACKAGE                  SOURCE                  CHANNEL
ir-lifecycle-operator   ibm-aiops-ir-lifecycle   ibm-cp-waiops-catalog   v4.4

NAME           PACKAGE        SOURCE                  CHANNEL
ibm-redis-cp   ibm-redis-cp   ibm-cp-waiops-catalog   v1.1

NAME                      PACKAGE                   SOURCE                  CHANNEL
cloud-native-postgresql   cloud-native-postgresql   ibm-cp-waiops-catalog   stable

NAME                        PACKAGE                       SOURCE                  CHANNEL
aiops-ibm-common-services   ibm-common-service-operator   ibm-cp-waiops-catalog   v4.3

NAME                         PACKAGE                     SOURCE                  CHANNEL
ibm-idp-config-ui-operator   ibm-commonui-operator-app   ibm-cp-waiops-catalog   v4.3

NAME                  PACKAGE               SOURCE                  CHANNEL
ibm-events-operator   ibm-events-operator   ibm-cp-waiops-catalog   v3

NAME              PACKAGE            SOURCE                  CHANNEL
ibm-im-operator   ibm-iam-operator   ibm-cp-waiops-catalog   v4.3

NAME                      PACKAGE                    SOURCE                  CHANNEL
ibm-im-mongodb-operator   ibm-mongodb-operator-app   ibm-cp-waiops-catalog   v4.2

NAME                      PACKAGE            SOURCE                  CHANNEL
ibm-platformui-operator   ibm-zen-operator   ibm-cp-waiops-catalog   v4.3

NAME                                       PACKAGE    SOURCE                  CHANNEL
operand-deployment-lifecycle-manager-app   ibm-odlm   ibm-cp-waiops-catalog   v4.2

______________________________________________________________
Subscriptions from openshift-operators namespace:

NAME           PACKAGE                     SOURCE                  CHANNEL
ibm-cert-mgr   ibm-cert-manager-operator   ibm-cp-waiops-catalog   v4.2

______________________________________________________________
OperandRequest instances:

NAMESPACE   NAME                   PHASE     CREATED AT
katamari    ibm-aiops-ai-manager   Running   2024-01-11T23:42:42Z

NAMESPACE   NAME                         PHASE     CREATED AT
katamari    ibm-aiops-aiops-foundation   Running   2024-01-11T23:42:42Z

NAMESPACE   NAME                   PHASE     CREATED AT
katamari    ibm-aiops-connection   Running   2024-01-11T23:42:42Z

NAMESPACE   NAME              PHASE     CREATED AT
katamari    ibm-iam-service   Running   2024-01-11T23:43:12Z

NAMESPACE   NAME              PHASE     CREATED AT
katamari    ibm-iam-request   Running   2024-01-11T23:40:35Z

______________________________________________________________
ODLM pod current status:

katamari                                           operand-deployment-lifecycle-manager-b47bd4d79-qdtdh                      1/1     Running     0              123m
______________________________________________________________
Orchestrator pod current status:

katamari                                           ibm-aiops-orchestrator-controller-manager-7c866ff66f-jhk8j                1/1     Running     0              127m
```

**Comment by siyer-123** [comment]
`oc waiops status-upgrade`: 

```
# oc waiops status-upgrade

Cloud Pak for AIOps v4.4 upgrade status:

______________________________________________________________

The following component(s) have finished upgrading:


KIND        NAMESPACE   NAME        STATUS       MESSAGE
AIOpsEdge   katamari    aiopsedge   Configured   all critical components are reporting healthy

KIND               NAMESPACE   NAME    VERSION   STATUS   MESSAGE
LifecycleService   katamari    aiops   4.4.0     Ready    All Services Ready

KIND      NAMESPACE   NAME               VERSION   STATUS   MESSAGE
AIOpsUI   katamari    aiopsui-instance   4.4.0     True     Ready

KIND   NAMESPACE   NAME      STATUS   MESSAGE
Kong   katamari    gateway   True     <none>

KIND        NAMESPACE   NAME        VERSION   STATUS      MESSAGE
AIManager   katamari    aimanager   4.4.0     Completed   AI Manager is ready

KIND                  NAMESPACE   NAME    VERSION   STATUS   MESSAGE
IssueResolutionCore   katamari    aiops   4.4.0     Ready    All Services Ready

KIND                         NAMESPACE   NAME    VERSION   STATUS   MESSAGE
AIOpsAnalyticsOrchestrator   katamari    aiops   4.4.0     Ready    All Services Ready

KIND     NAMESPACE   NAME         STATUS
Tunnel   katamari    sre-tunnel   True

KIND   NAMESPACE   NAME             VERSION   STATUS
ASM    katamari    aiops-topology   2.20.0    OK

______________________________________________________________

Hint: for a more detailed printout of component statuses, run `oc waiops status` or `oc waiops status-all`.
```

**Review by lsalazar1 — APPROVED** [review]

**Comment by siyer-123** [comment]
`oc waiops status-upgrade`: 

```
# oc waiops status-upgrade

Cloud Pak for AIOps v4.4 upgrade status:

______________________________________________________________

The following component(s) have finished upgrading:


KIND        NAMESPACE   NAME        STATUS       MESSAGE
AIOpsEdge   katamari    aiopsedge   Configured   all critical components are reporting healthy

KIND               NAMESPACE   NAME    VERSION   STATUS   MESSAGE
LifecycleService   katamari    aiops   4.4.0     Ready    All Services Ready

KIND      NAMESPACE   NAME               VERSION   STATUS   MESSAGE
AIOpsUI   katamari    aiopsui-instance   4.4.0     True     Ready

KIND   NAMESPACE   NAME      STATUS   MESSAGE
Kong   katamari    gateway   True     <none>

KIND        NAMESPACE   NAME        VERSION   STATUS      MESSAGE
AIManager   katamari    aimanager   4.4.0     Completed   AI Manager is ready

KIND                  NAMESPACE   NAME    VERSION   STATUS   MESSAGE
IssueResolutionCore   katamari    aiops   4.4.0     Ready    All Services Ready

KIND                         NAMESPACE   NAME    VERSION   STATUS   MESSAGE
AIOpsAnalyticsOrchestrator   katamari    aiops   4.4.0     Ready    All Services Ready

KIND     NAMESPACE   NAME         STATUS
Tunnel   katamari    sre-tunnel   True

KIND   NAMESPACE   NAME             VERSION   STATUS
ASM    katamari    aiops-topology   2.20.0    OK

______________________________________________________________

Hint: for a more detailed printout of component statuses, run `oc waiops status` or `oc waiops status-all`.

```

**Comment by siyer-123** [comment]
```
# oc waiops status

Cloud Pak for AIOps v4.4 installation status:
  Componentstatus:
    Aimanager:                       Ready
    Aiopsanalyticsorchestrator:      Ready
    Aiopsedge:                       Ready
    Aiopsui:                         Ready
    Asm:                             Ready
    Baseui:                          Ready
    Cluster:                         Ready
    Commonservice:                   Ready
    Elasticsearch:                   Ready
    Flinkcluster:                    Ready
    Issueresolutioncore:             Ready
    Kafka:                           Ready
    Kong:                            Ready
    Lifecycleservice:                Ready
    Tunnel:                          Ready
    Zenservice:                      Ready
  Custom Profile Configmap:          aiops-custom-size-profile
  Custom Profile Validation Status:  Custom profile configmap not found, continue installation process without customization
  Image Pull Secret:                 Global
  Licenseacceptance:                 Accepted
  Locations:
    Cloud Pak Ui URL:      <Cloud Pak Ui URL>
    Cs Admin Hub URL:      <Cs Admin Hub URL>
  Phase:                   Running
  Size:                    small
  Storageclass:            <Storageclass>
  Storageclasslargeblock:  <Storageclasslargeblock>
```

**Pull request merged**
